# Generated by Django 4.0.4 on 2022-05-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_datablog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datablog',
            name='category',
        ),
    ]
