# Generated by Django 4.0.4 on 2022-05-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_datablog1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datablog',
            name='descriptions',
            field=models.TextField(max_length=200),
        ),
        migrations.DeleteModel(
            name='DataBlog1',
        ),
    ]
